export default {
    channels: [
        { name: 'Telestar-1', id: 'telestar-1' },
        { name: 'CNN', id: 'cnn' },
        { name: 'DW', id: 'deutsche-welle' },
        { name: 'TV5', id: 'tv5-monde' },
        { name: 'Duna TV', id: 'duna-tv' },
        { name: 'France 24', id: 'france-24' },
        { name: 'KanalD', id: 'kanal-d' },
        { name: 'KanalD2', id: 'kanal-d2' },
        { name: 'TVR1', id: 'tvr1' },
        { name: 'TVR2', id: 'tvr2' },
        { name: 'Prima', id: 'prima-tv' },
        { name: 'A7-tv', id: 'a7-tv' },
        { name: 'DaVinci', id: 'davinci-learning' },
        { name: 'Teen-Nick', id: 'teen-nick' },
        { name: 'jimjam', id: 'jimjam' },
        { name: 'Cartoonito', id: 'cartoonito' },
        { name: 'Nick-toons', id: 'nick-toons' },
        { name: 'Nick-JR', id: 'nick-jr' },
        { name: 'CartoonNet', id: 'cartoon-network' },
        { name: 'Minimax', id: 'minimax' },
        { name: 'DisneyJr', id: 'disney-junior' },
        { name: 'Nickelodeon', id: 'nickelodeon' },
        { name: 'Disney', id: 'disney-channel' },
        { name: 'Tralala', id: 'tralala-tv' },
        { name: 'Digi life', id: 'digi-life' },
        { name: 'Digi world', id: 'digi-world' },
        { name: 'Digi animal', id: 'digi-animal-world' },
        { name: 'Kapital tv', id: 'kapital-tv' },
        { name: 'Agro tv', id: 'agro-tv' },
        { name: 'ViasatNat', id: 'viasat-nature' },
        { name: 'National Geographic Wild', id: 'national-geographic-wild' },
        { name: 'Discovery', id: 'discovery-channel' },
        { name: 'National Geographic', id: 'national-geographic' },
        { name: 'Viasat History', id: 'viasat-history' },
        { name: 'Cinethronix', id: 'cinethronix' },
        { name: 'HistoryChannel', id: 'history-channel' },
        { name: 'Viasat explorer', id: 'viasat-explorer' },
        { name: 'TLC', id: 'tlc' },
        { name: 'BBC Earth', id: 'bbc-earth' },
        { name: 'Medika', id: 'medika' },
        { name: 'Maria TV', id: 'maria-tv' },
        { name: 'Prima history', id: 'prima-history' },
        { name: 'digi24', id: 'digi24' },
        { name: 'Ncn', id: 'ncn-tv' },
        { name: 'aleph', id: 'aleph-news' },
        { name: 'B1TV', id: 'b1tv' },
        { name: 'Romaniatv', id: 'romania-tv' },
        { name: 'Realitatea', id: 'realitatea-tv' },
        { name: 'Prima news', id: 'prima-news' },
        { name: 'Global-news', id: 'global-news' },
        { name: 'Sky-news', id: 'sky-news' },
        { name: 'U-tv', id: 'u-tv' },
        { name: 'Mezzo', id: 'mezzo' },
        { name: 'Favorit', id: 'favorit' },
        { name: 'Magic-tv', id: 'magic-tv' },
        { name: 'Rock-tv', id: 'rock-tv' },
        { name: 'Slager-tv', id: 'slager-tv' },
        { name: 'MTVeu', id: 'mtv-europe' },
        { name: 'Hit-music', id: 'hit-music-channel' },
        { name: 'MTV-00s', id: 'mtv-00s' },
        { name: 'KISS', id: 'kiss-tv' },
        { name: 'MusicChannel', id: 'music-channel' },
        { name: 'Etno', id: 'etno-tv' },
        { name: 'Taraf', id: 'taraf-tv' },
        { name: 'Hora', id: 'hora-tv' },
        { name: 'Mooz-dance', id: 'mooz-dance' },
        { name: 'Rapsodia-tv', id: 'rapsodia-tv' },
        { name: 'E-entertainment', id: 'e-entertainment' },
        { name: 'Travel mix', id: 'travel-mix-channel' },
        { name: 'CBS real', id: 'cbs-reality' },
        { name: 'Paprika', id: 'tv-paprika' },
        { name: 'Travel', id: 'travel-channel' },
        { name: 'Fishing hunting', id: 'fishing-and-hunting' },
        { name: 'GHTV', id: 'hgtv' },
        { name: 'Arcadia tv', id: 'arcadia-tv' }
    ],
    port: 3000,
    executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
    defaultViewport: {
        width: 640,
        height: 360,
    },
}
